apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-volume
  namespace: monitoring
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-volume
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/