apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
  labels:
    type: local
  namespace: monitoring
spec:
  storageClassName: grafana
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/data/grafana"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: grafana-pvc
  labels:
    name: grafana
  namespace: monitoring
spec:    
   storageClassName: grafana
   accessModes:
    - ReadWriteOnce
   resources:
    requests:   
      storage: 2Gi