{
 "title": "Cluster",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster or Node CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_load1{}, kubernetes_node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",kubernetes_node=~\"^$Node$\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable_bytes{kubernetes_node=~\"^$Node$\"})/ sum(node_memory_MemTotal_bytes{kubernetes_node=~\"^$Node$\"})) * 100"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",kubernetes_node=~\"^$Node$\"})\n     - sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\",kubernetes_node=~\"^$Node$\"})) / sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",kubernetes_node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (avg(irate(node_cpu_seconds_total{mode=\"idle\",kubernetes_node=~\"^$Node$\"}[5m])))) * sum(machine_cpu_cores{instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{device!~\"rootfs|HarddiskVolume.+\",kubernetes_node=~\"^$Node$\"}) - sum(node_memory_MemAvailable_bytes{device!~\"rootfs|HarddiskVolume.+\",kubernetes_node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",kubernetes_node=~\"^$Node$\"})\n     - sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\",kubernetes_node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",kubernetes_node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "CPU usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1- (avg(irate(node_cpu_seconds_total{mode=\"idle\",}[5m])))",
     "legendFormat": "{{cluster}}"
    },
    {
     "expr": "1- (avg(irate(node_cpu_seconds_total{mode=\"idle\",kubernetes_node=~\"^$Node$\"}[5m])) by (kubernetes_node))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - sum(node_memory_MemAvailable_bytes{}) / sum(node_memory_MemTotal_bytes{}))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "100 * (1- sum(node_memory_MemAvailable_bytes{kubernetes_node=~\"^$Node$\"}) by (kubernetes_node) / sum(node_memory_MemTotal_bytes{kubernetes_node=~\"^$Node$\"}) by (kubernetes_node))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",})\n     - sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\",})\n    ) / sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",}) * 100 ",
     "legendFormat": "{{ cluster }}"
    },
    {
     "expr": "((sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",kubernetes_node=~\"^$Node$\"}) by (kubernetes_node) - sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\",kubernetes_node=~\"^$Node$\"}) by (kubernetes_node)) / sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",kubernetes_node=~\"^$Node$\"}) by (kubernetes_node)) * 100\n",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Numbers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$Node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", node=~\"$Node\", status!=\"true\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\", node=~\"$Node\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", node=~\"$Node\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "PID Pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\", node=~\"$Node\", status!=\"false\"})"
    }
   ]
  },
  {
   "title": "Unschedulable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Out of Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$Node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Network Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"NetworkUnavailable\", node=~\"$Node\", status!=\"false\"})"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\".*\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\".*\"})"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Jobs Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\".*\"})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*\", phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts{namespace=~\".*\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\".*\", kubernetes_node=~\"$Node\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\".*\", kubernetes_node=~\"$Node\", unit=\"byte\"})"
    }
   ]
  },
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{instance=~\"$Node\"}[5m]))",
     "legendFormat": "{{instance}} Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{instance=~\"$Node\"}[5m])) ",
     "legendFormat": "{{instance}} Sent"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Pods CPU usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",instance=~\"^$Node$\"}[5m])) by (pod)",
     "legendFormat": "{{pod }}"
    }
   ]
  },
  { "title": "System services CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "System services CPU usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{systemd_service_name!=\"\",instance=~\"^$Node$\"}[5m])) by (systemd_service_name)",
     "legendFormat": "{{ systemd_service_name }}"
    }
   ]
  },
  { "title": "Containers CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Containers CPU usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",instance=~\"^$Node$\"}[5m])) by (container,pod)",
     "legendFormat": "pod: {{pod }} | {{ container }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",instance=~\"^$Node$\"}[5m])) by (node, container)",
     "legendFormat": "docker: {{ node }} | {{ container }}"
    }
   ]
  },
  { "title": "All processes CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "All processes CPU usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace!=\"\",pod!=\"\",container!=\"\",instance=~\"^$Node$\"}[5m])) by (namespace,pod)",
     "legendFormat": "{{ namespace }}:{{pod }}"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod!=\"\",instance=~\"^$Node$\"}) by (pod)",
     "legendFormat": "{{pod }}"
    }
   ]
  },
  { "title": "System services memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "System services memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{systemd_service_name!=\"\",instance=~\"^$Node$\"}) by (systemd_service_name)",
     "legendFormat": "{{ systemd_service_name }}"
    }
   ]
  },
  { "title": "Containers memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod!=\"\",container!=\"POD\",container!=\"\",instance=~\"^$Node$\"}) by (container,pod)",
     "legendFormat": "pod: {{pod }} | {{ container }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",container!=\"POD\",kubernetes_node=~\"^$Node$\"}) by (node, container)",
     "legendFormat": "docker: {{ node }} | {{ container }}"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_node=~\"^$Node$\"}) by (node, rkt_container_name)",
     "legendFormat": "rkt: {{ node }} | {{ rkt_container_name }}"
    }
   ]
  },
  { "title": "All processes memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "All processes memory usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "sum (rate (container_memory_working_set_bytes{namespace!=\"\",pod!=\"\",container!=\"\",instance=~\"^$Node$\"}[5m])) by (namespace,pod)",
     "legendFormat": "{{ namespace }}:{{pod}}"
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "Pods network I/O (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod!=\"\",instance=~\"^$Node$\"}[5m])) by (pod)",
     "legendFormat": "-> {{pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod!=\"\",instance=~\"^$Node$\"}[5m])) by (pod)",
     "legendFormat": "<- {{pod }}"
    }
   ]
  },
  { "title": "Containers network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 } },
  {
   "title": "Containers network I/O (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{container!=\"\",pod!=\"\",instance=~\"^$Node$\"}[5m])) by (container,pod)",
     "legendFormat": "-> pod: {{pod }} | {{ container }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{container!=\"\",pod!=\"\",instance=~\"^$Node$\"}[5m])) by (container,pod)",
     "legendFormat": "<- pod: {{pod }} | {{ container }}"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{container!=\"\",pod!=\"\",instance=~\"^$Node$\"}[5m])) by (node, name, image)",
     "legendFormat": "-> docker: {{ node }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{container!=\"\",pod!=\"\",instance=~\"^$Node$\"}[5m])) by (node, name, image)",
     "legendFormat": "<- docker: {{ node }} | {{ image }} ({{ name }})"
    }
   ]
  },
  { "title": "All processes network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 } },
  {
   "title": "All processes network I/O (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{instance=~\"^$Node$\"}[5m])) by (namespace,pod)",
     "legendFormat": "-> {{ namespace }}:{{pod}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{instance=~\"^$Node$\"}[5m])) by (namespace,pod)",
     "legendFormat": "<- {{ namespace }}:{{pod}}"
    }
   ]
  }
 ]
}