{
 "title": "DaemonSet",
 "description": "Kubernetes DaemonSet Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "daemonset_namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_daemonset_metadata_generation{}, namespace)"
    }
   },
   {
    "name": "daemonset_name",
    "label": "DaemonSet",
    "query": {
     "query": "label_values(kube_daemonset_metadata_generation{namespace=\"$daemonset_namespace\"}, daemonset)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=\"$daemonset_namespace\", pod=~\"$daemonset_name.*\", container!=\"POD\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_daemonset_status_desired_number_scheduled{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(kube_daemonset_status_number_available{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "{{ daemonset }}"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_daemonset_metadata_generation{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "DaemonSet Create Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_daemonset_created{namespace=\"$daemonset_namespace\",daemonset=\"$daemonset_name\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$daemonset_namespace\",pod=~\"$daemonset_name.*\",container!=\"\",container!=\"POD\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$daemonset_namespace\",pod=~\"$daemonset_name.*\",container!=\"\",container!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$daemonset_namespace\",pod=~\"$daemonset_name.*\"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace=\"$daemonset_namespace\",pod=~\"$daemonset_name.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (container, pod) (rate(container_cpu_usage_seconds_total{namespace=\"$daemonset_namespace\",pod=~\"$daemonset_name.*\",container=~\"$container\",container!=\"\",container!=\"POD\"}[5m]))",
     "legendFormat": "{{container, pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod, container) (container_memory_working_set_bytes{namespace=\"$daemonset_namespace\",pod=~\"$daemonset_name.*\",container=~\"$container\",container!=\"\",container!=\"POD\"})",
     "legendFormat": "{{pod container }}"
    }
   ]
  },
  {
   "title": "Replicas Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kube_daemonset_status_number_ready{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Ready"
    },
    {
     "expr": "avg(kube_daemonset_status_number_available{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "avg(kube_daemonset_status_number_unavailable{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "avg(kube_daemonset_status_number_misscheduled{daemonset=\"$daemonset_name\",namespace=\"$daemonset_namespace\"}) without (instance, pod)",
     "legendFormat": "Misscheduled"
    }
   ]
  }
 ]
}