{
 "title": "Kubernetes / Horizontal Pod Autoscaler",
 "description": "A quick and simple dashboard for viewing how your horizontal pod autoscaler is doing.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_metadata_generation{}, namespace)"
    }
   },
   {
    "name": "hpa",
    "label": "Name",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_labels{namespace=\"$namespace\"}, horizontalpodautoscaler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{ namespace=\"$namespace\", horizontalpodautoscaler=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{ namespace=\"$namespace\", horizontalpodautoscaler=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Min Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{  namespace=\"$namespace\", horizontalpodautoscaler=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Max Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{ horizontalpodautoscaler=\"$hpa\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{ horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Desired"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{ horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{job=\"kube-state-metrics\", horizontalpodautoscaler=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Min"
    }
   ]
  }
 ]
}