{
 "title": "K8S LoadBalancer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "deployment_namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation{}, namespace)"
    }
   },
   {
    "name": "deployment_name",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation{namespace=\"$deployment_namespace\"}, deployment)"
    }
   },
   {
    "name": "internal_lb",
    "label": "internal-lb",
    "query": "resource_arns(us-east-1,elasticloadbalancing:loadbalancer, {\"ingress.k8s.aws/stack\" :[\"$deployment_namespace/$deployment_name\"], \"elbv2.k8s.aws/cluster\" :[\"$cluster\"]})"
   },
   {
    "name": "public_lb",
    "label": "public-lb",
    "query": "resource_arns(us-east-1,elasticloadbalancing:loadbalancer, {\"ingress.k8s.aws/stack\" :[\"$deployment_namespace/$deployment_name-public\"], \"elbv2.k8s.aws/cluster\" :[\"$cluster\"]})"
   }
  ]
 },
 "panels": [
  {
   "title": "HPA",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) ",
     "legendFormat": "Available",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Desired",
     "region": "default",
     "statistic": "Average"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Unavailable",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 6 },
   "options": {
    "content": "\n# Public LB Metrics\n\nMétricas de loadbalancer público (caso haja).\n\n\n\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "options": {
    "content": "\n# Internal LB Metrics\n\nMétricas de loadbalancer interno (caso haja).\n\n\n\n"
   }
  },
  {
   "title": "Target Response Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$public_lb" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "LoadBalancer": "$public_lb" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "LoadBalancer": "$public_lb" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "p95"
    },
    {
     "dimensions": { "LoadBalancer": "$public_lb" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "p99"
    }
   ]
  },
  {
   "title": "Target Response TIme",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$internal_lb" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "LoadBalancer": "$internal_lb" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "LoadBalancer": "$internal_lb" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "p95"
    },
    {
     "dimensions": { "LoadBalancer": "$internal_lb" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "p99"
    }
   ]
  },
  {
   "title": "Public LB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Request",
     "dimensions": { "LoadBalancer": "$public_lb" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "alias": "Target 2xx",
     "dimensions": { "LoadBalancer": "$public_lb" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "Target 5xx",
     "dimensions": { "LoadBalancer": "$public_lb" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "Target 4xx",
     "dimensions": { "LoadBalancer": "$public_lb" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Internal LB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Request",
     "dimensions": { "LoadBalancer": "$internal_lb" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "alias": "Target 2xx",
     "dimensions": { "LoadBalancer": "$internal_lb" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "Target 5xx",
     "dimensions": { "LoadBalancer": "$internal_lb" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "Target 4xx",
     "dimensions": { "LoadBalancer": "$internal_lb" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Public Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ELB 5xx",
     "dimensions": { "LoadBalancer": "$public_lb" },
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "alias": "ELB 4xx",
     "dimensions": { "LoadBalancer": "$public_lb" },
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "Target Conn Error",
     "dimensions": { "LoadBalancer": "$public_lb" },
     "metricName": "TargetConnectionErrorCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Internal Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ELB 5xx",
     "dimensions": { "LoadBalancer": "$internal_lb" },
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "alias": "ELB 4xx",
     "dimensions": { "LoadBalancer": "$internal_lb" },
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "alias": "Target Conn Error",
     "dimensions": { "LoadBalancer": "$internal_lb" },
     "metricName": "TargetConnectionErrorCount",
     "namespace": "AWS/ApplicationELB",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  }
 ]
}