{
 "title": "Node Status",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "All",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kube_node_labels{})", "legendFormat": "Total" },
    {
     "expr": "sum(kube_node_labels{label_spotinst_io_node_lifecycle=\"spot\"})",
     "legendFormat": "SPOT"
    },
    {
     "expr": "sum(kube_node_labels{label_spotinst_io_node_lifecycle!=\"spot\"})",
     "legendFormat": "OD"
    }
   ]
  },
  {
   "title": "Flavor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Instance OD by Flavor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (label_beta_kubernetes_io_instance_type) (kube_node_labels{label_spotinst_io_node_lifecycle!=\"spot\"})",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}}"
      }
     ]
    },
    {
     "title": "Instance SPOT by Flavor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (label_beta_kubernetes_io_instance_type) (kube_node_labels{label_spotinst_io_node_lifecycle=\"spot\"})",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Instance OD by Zone",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (label_failure_domain_beta_kubernetes_io_zone) (kube_node_labels{label_spotinst_io_node_lifecycle!=\"spot\"})",
       "legendFormat": "{{label_failure_domain_beta_kubernetes_io_zone}}"
      }
     ]
    },
    {
     "title": "Instance SPOT by Zone",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (label_failure_domain_beta_kubernetes_io_zone) (kube_node_labels{label_spotinst_io_node_lifecycle=\"spot\"})",
       "legendFormat": "{{label_failure_domain_beta_kubernetes_io_zone}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zone/Flavor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Instance SPOT by Zone/Flavor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (label_failure_domain_beta_kubernetes_io_zone,label_beta_kubernetes_io_instance_type) (kube_node_labels{label_spotinst_io_node_lifecycle=\"spot\"})",
       "legendFormat": "{{label_failure_domain_beta_kubernetes_io_zone}} - {{label_beta_kubernetes_io_instance_type}}"
      }
     ]
    },
    {
     "title": "Instance OD by Zone/Flavor",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (label_failure_domain_beta_kubernetes_io_zone,label_beta_kubernetes_io_instance_type) (kube_node_labels{label_spotinst_io_node_lifecycle!=\"spot\"})",
       "legendFormat": "{{label_failure_domain_beta_kubernetes_io_zone}} - {{label_beta_kubernetes_io_instance_type}}"
      }
     ]
    }
   ]
  }
 ]
}