{
 "title": "StatefulSet",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "statefulset_name",
    "label": "StatefulSet",
    "query": {
     "query": "label_values(kube_statefulset_metadata_generation{}, statefulset)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$statefulset_name.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$statefulset_name.*\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"$statefulset_name.*\"}[5m])) + sum(rate(container_network_receive_bytes_total{pod=~\"$statefulset_name.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"$statefulset_name.*\",container!=\"POD\",container!=\"\"}[5m]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"$statefulset_name.*\",container!=\"POD\",container!=\"\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"$statefulset_name.*\"}[5m]) + rate(container_network_receive_bytes_total{pod=~\"$statefulset_name.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$statefulset_name.*\",container!=\"POD\",container!=\"\"}[5m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"$statefulset_name.*\",container!=\"POD\",container!=\"\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{pod=~\"$statefulset_name.*\",container!=\"POD\",container!=\"\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$statefulset_name.*\",container!=\"POD\",container!=\"\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{pod=~\"$statefulset_name.*\",container!=\"POD\",container!=\"\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{pod=~\"$statefulset_name.*\",container!=\"POD\",container!=\"\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$statefulset_name\",})"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas{statefulset=\"$statefulset_name\",})"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_status_observed_generation{statefulset=\"$statefulset_name\",})"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_metadata_generation{statefulset=\"$statefulset_name\",})"
    }
   ]
  },
  {
   "title": "CPU throttle by Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"$statefulset_name.*\",container!=\"POD\",container!=\"\"}[5m]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas{statefulset=\"$statefulset_name\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$statefulset_name\"}) without (instance, pod)",
     "legendFormat": "Desired"
    }
   ]
  }
 ]
}